/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GeneralFaqsRouteImport } from './routes/general-faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ToursSlugShareImageRouteImport } from './routes/tours.$slug.share-image'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralFaqsRoute = GeneralFaqsRouteImport.update({
  id: '/general-faqs',
  path: '/general-faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugShareImageRoute = ToursSlugShareImageRouteImport.update({
  id: '/share-image',
  path: '/share-image',
  getParentRoute: () => ToursSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/general-faqs': typeof GeneralFaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/$slug/share-image': typeof ToursSlugShareImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/general-faqs': typeof GeneralFaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tours': typeof ToursIndexRoute
  '/tours/$slug/share-image': typeof ToursSlugShareImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/general-faqs': typeof GeneralFaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/upcoming': typeof UpcomingRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tours/$slug': typeof ToursSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/tours/$slug/share-image': typeof ToursSlugShareImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/general-faqs'
    | '/privacy-policy'
    | '/shop'
    | '/stories'
    | '/terms-and-conditions'
    | '/upcoming'
    | '/admin/login'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/admin/'
    | '/blog/'
    | '/tours/'
    | '/tours/$slug/share-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/general-faqs'
    | '/privacy-policy'
    | '/shop'
    | '/stories'
    | '/terms-and-conditions'
    | '/upcoming'
    | '/admin/login'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/admin'
    | '/blog'
    | '/tours'
    | '/tours/$slug/share-image'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/general-faqs'
    | '/privacy-policy'
    | '/shop'
    | '/stories'
    | '/terms-and-conditions'
    | '/upcoming'
    | '/admin/login'
    | '/blog/$slug'
    | '/tours/$slug'
    | '/admin/'
    | '/blog/'
    | '/tours/'
    | '/tours/$slug/share-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GeneralFaqsRoute: typeof GeneralFaqsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShopRoute: typeof ShopRoute
  StoriesRoute: typeof StoriesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UpcomingRoute: typeof UpcomingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToursSlugRoute: typeof ToursSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-faqs': {
      id: '/general-faqs'
      path: '/general-faqs'
      fullPath: '/general-faqs'
      preLoaderRoute: typeof GeneralFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug/share-image': {
      id: '/tours/$slug/share-image'
      path: '/share-image'
      fullPath: '/tours/$slug/share-image'
      preLoaderRoute: typeof ToursSlugShareImageRouteImport
      parentRoute: typeof ToursSlugRoute
    }
  }
}

interface ToursSlugRouteChildren {
  ToursSlugShareImageRoute: typeof ToursSlugShareImageRoute
}

const ToursSlugRouteChildren: ToursSlugRouteChildren = {
  ToursSlugShareImageRoute: ToursSlugShareImageRoute,
}

const ToursSlugRouteWithChildren = ToursSlugRoute._addFileChildren(
  ToursSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GeneralFaqsRoute: GeneralFaqsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShopRoute: ShopRoute,
  StoriesRoute: StoriesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UpcomingRoute: UpcomingRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToursSlugRoute: ToursSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
